name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Dependencies
        run: go mod tidy

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.2

      - name: Run golangci-lint
        run: golangci-lint run ./...
        continue-on-error: true

      - name: Run Tests with Coverage
        run: |
          go test -coverprofile=cover.out -coverpkg=./... ./...
          go tool cover -func=cover.out

          coverage=$(go tool cover -func=cover.out | grep total: | awk '{print substr($3, 1, length($3)-1)}')
          echo "Total coverage: $coverage%"

          cov_int=$(echo "$coverage >= 80.0" | bc -l)
          if [ "$cov_int" -ne 1 ]; then
            echo "Coverage too low: $coverage% (required: >= 80%)"
            exit 1
          fi

          echo "✅ Coverage is sufficient: $coverage%"
